name: CI/CD - Credit Card Fraud ML

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 1.5️⃣ Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 2️⃣ Authenticate to GCP
      - name: Set up GCP credentials
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 3️⃣ Configure Docker for Artifact Registry
      - name: Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      # 4️⃣ Build Docker image
      - name: Build Docker image
        run: |
          IMAGE="us-central1-docker.pkg.dev/durable-unity-468703-a2/my-repo/demo_log:${GITHUB_SHA}"
          docker build -t $IMAGE .
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      # 5️⃣ Push Docker image to Artifact Registry
      - name: Push Docker image
        run: docker push $IMAGE

      # 6️⃣ Run Fairlearn metrics
      - name: Run Fairlearn Metrics
        run: python fairlearn_metrics.py

      # 7️⃣ Run monitoring (SHAP plots)
      - name: Run Monitoring & SHAP
        run: python monitoring.py

      # 8️⃣ Upload SHAP plots as artifacts
      - name: Upload SHAP plots
        uses: actions/upload-artifact@v4
        with:
          name: shap-plots
          path: |
            shap_summary.png
            shap_force_plot.png

      # 9️⃣ Get GKE credentials
      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: demo-log-ml-cluster-1
          location: us-central1-a
          project_id: durable-unity-468703-a2

      # 🔟 Deploy to GKE
      - name: Deploy to GKE
        run: |
          # Update deployment.yaml with new image tag
          sed -i "s|image: .*|image: $IMAGE|" deployment.yaml

          # Apply manifests
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
          kubectl apply -f hpa.yaml

